DROP TABLE IF EXISTS LANGUAGE_MAP_ENTITY;  
CREATE TABLE LANGUAGE_MAP_ENTITY ( 
id INT NOT NULL;
source_language VARCHAR(50) NOT NULL,  
target_language VARCHAR(50) NOT NULL,  
source_text VARCHAR(500) NOT NULL,
target_text VARCHAR(1500) NOT NULL
);  